name: CI

on: [push, pull_request]

jobs:
  build:
    name: JDK ${{ matrix.java_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java_version: [1.8, 9, 10, 11, 12, 13, 14]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java_version }}
      - name: Configure Gradle
        # Initial gradle configuration, install dependencies, etc
        run: ./gradlew help
      - name: Spot check
        # Run spotless first to fail fast on spotless issues
        run: ./gradlew spotlessCheck --stacktrace
      - name: Build project
        run: ./gradlew assemble --stacktrace
      - name: Run tests
        run: ./gradlew test --stacktrace
      - name: Final checks
        run: ./gradlew check --stacktrace
      - name: Upload snapshot (main only)
        run: ./gradlew uploadArchives -PSONATYPE_NEXUS_USERNAME="$SONATYPE_NEXUS_USERNAME" -PSONATYPE_NEXUS_PASSWORD="$SONATYPE_NEXUS_PASSWORD"
        env:
          SONATYPE_NEXUS_USERNAME: ${{ secrets.SonatypeUsername }}
          SONATYPE_NEXUS_PASSWORD: ${{ secrets.SonatypePassword }}
        if: success() && github.ref == 'refs/heads/main' && github.event_name != 'pull_request' && matrix.java_version == '1.8'
